zalando-zmon/zmon-controller

zmon-controller-app/src/main/java/de/zalando/zmon/security/simple/SimpleAuthorityService.java, zmon-github-integration/src/main/java/org/zalando/github/zmon/security/IsAllowedOrgaSignupCondition.java, zmon-github-integration/src/main/java/org/zalando/github/zmon/security/IsAllowedUserSignupCondition.java, zmon-security-common/src/main/java/org/zalando/zmon/security/service/SimpleSocialUserDetailsService.java
@hjacobs @Jan-M Please review.
Edit dashboard is fixed now
=> Fix edit dashboard

zmon-controller-ui/views/dashboardDefinitions.html
@hjacobs @Jan-M Please review. This should fix the delete redirect
=> Fix delete UI

zmon-controller-app/src/main/java/de/zalando/zmon/controller/ZMonRestService.java, zmon-controller-app/src/main/resources/templates/grafana2.html, zmon-controller-ui/grafana2/app/plugins/datasource/elasticsearch/datasource.js
last changes on grafana2 angular app and comments on dummy endpoints to further develop
=> Feature grafana2

zmon-common/pom.xml, zmon-controller-app/src/main/java/org/zalando/zmon/config/RedisPoolConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/annotation/RedisWrite.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/redis/DefaultRedisProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/redis/WriteRedisProperties.java, zmon-controller-app/src/test/java/org/zalando/zmon/config/RedisConfigTest.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/AlertServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/DashboardServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/HistoryServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ServiceTestConfiguration.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplIT.java, zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-security-common/pom.xml, zmon-security-common/src/main/java/org/zalando/zmon/security/ZmonAuthenticationEntrypoint.java, zmon-security-common/src/test/java/org/zalando/zmon/security/MediaTypeParserTest.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
=> X-FRAME-OPTIONS header should be disabled to allow ZMON in IFrames

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/styles/forms.css, zmon-controller-ui/views/alertDetails.html
This should be done on all other tables, I will open an issue for that.
=> #73 enable sorting of alert details table by clicking on headers

zmon-controller-ui/js/controllers/AlertDefinitionCtrl.js, zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionCtrl.js, zmon-controller-ui/js/controllers/DashboardDefinitionCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/views/alertDefinitions.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/checkDefinitions.html, zmon-controller-ui/views/dashboardDefinitions.html, zmon-controller-ui/views/trialRun.html
adds sorting capabilities to all tables, as donde in #73 for alert details page.
=> 79 sort on all tables

zmon-controller-app/src/test/resources/test.properties
Sorry for the failing tests, this fixes it :-)
=> #90 fix test datasource properties

zmon-controller-app/src/main/java/org/zalando/zmon/config/CorsConfiguration.java, zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
=> add a cors-configuration

zmon-controller-app/src/main/resources/templates/index.html
For unknown reasons it must have a "tooltip-trigger" argument.
=> #62 fix status tooltip on navbar

zmon-controller-ui/js/controllers/CloudCtrl.js, zmon-controller-ui/views/cloud.html
angularjs used to sort object keys on ng-repeat, but not any longer.
=> 62 angularjs update

zmon-controller-app/src/main/java/org/kairosdb/client/KairosDBOAuthHttpClient.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/KairosDBProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/KairosDBController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java, zmon-controller-app/src/main/resources/config/application-zauth.yml, zmon-controller-app/src/main/resources/config/application.yml
=> #111 use OAuth for check charts too

zmon-controller-ui/js/controllers/EntityCtrl.js
=> fix variable reference

.gitattributes
Most important PR ever :smiley:
=> ignore vendored JS libs

zmon-controller-ui/js/controllers/EntityCtrl.js, zmon-controller-ui/styles/main.css, zmon-controller-ui/views/entities.html
Show downtimed alert entites as grey.
=> consider downtimes in entity view

zmon-controller-ui/js/controllers/AlertDefinitionCtrl.js, zmon-controller-ui/views/alertDefinitions.html, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/checkDefinitions.html
Users sometimes forget to add alerts and wonder why no data is collected --- this new hint should help them :smile: .
=> add hint about adding an alert definition

zmon-controller-ui/js/controllers/CloudCtrl.js, zmon-controller-ui/js/directives/dashboardWidget.js, zmon-controller-ui/lib/jsonpath/jsonpath.js
even though 0.8.0 is the final version on Steffan Grossner repository ( http://goessner.net/ ), some things seem to break with the downgrade (from our previous 0.8.5 version which I have no idea where it was taken from, but works).
=> revert jsonpath to 0.8.5

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java, zmon-controller-app/src/main/resources/grafana/dynamic-dashboard.json, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaControllerTest.java, zmon-controller-ui/js/controllers/DashboardCtrl.js, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/dashboard.html
Replace links to check-charts with links to Grafana
=> Issue 147 dynamic grafana dashboard

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java, zmon-controller-app/src/main/resources/grafana/dynamic-dashboard.json, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaControllerTest.java
This adds small dropdown links to the first panel to easily jump to the check definition and entity page.
=> #147 add links to check def and entity

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/styles/forms.css, zmon-controller-ui/views/alertDetails.html
=> 149 localstorage of alert detail's entity filter

zmon-security-common/src/main/java/org/zalando/zmon/security/jwt/JWTService.java
Important to mitigate XSS: https://www.owasp.org/index.php/HTTPOnly
=> set cookie httpOnly flag (https://www.owasp.org/index.php/HTTPOnly)

zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java, zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractorTest.java
To not hit rate limits of team service :smirk:
=> only load teams for /employees realm

zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-security-common/src/main/java/org/zalando/zmon/security/service/SimpleSocialUserDetailsService.java, zmon-security-common/src/test/java/org/zalando/zmon/security/service/SimpleSocialUserDetailsServiceTest.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
=> Fix team-reload when user loaded from UserDetailsService

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/HistoryServiceImpl.java
Support the new query parameters which were introduced in https://github.com/zalando-zmon/zmon-eventlog-service/pull/7
=> pass thru eventlog query params

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiTest.java
Catch PSQL check constraint violations and return bad request.
Fixes #214.
=> Feature check entity

run-dev.sh, zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/datasource.js, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/module.js, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/partials/config.html, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/partials/query.editor.html, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/partials/query.options.html, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/plugin.json, zmon-controller-ui/grafana/public/plugins/grafana-alertstate-datasource/query_ctrl.js
=> first hack to graph alert state over time

database/zmon/20_api/05_stored_procedures/11_create_or_update_entity.sql, database/zmon/20_api/05_stored_procedures/14_delete_entities.sql, zmon-common/src/main/java/org/zalando/zmon/persistence/EntitySProcService.java, zmon-controller-app/src/main/java/org/zalando/zmon/ZmonApplication.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/ResourceNotFoundException.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/NoOpEventLog.java, zmon-controller-app/src/test/java/org/zalando/test/RedisConfigTest.java, zmon-controller-app/src/test/java/org/zalando/test/ServiceTestConfiguration.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiTest.java, zmon-controller-app/src/test/java/org/zalando/zmon/config/TestConfiguration.java, zmon-controller-app/src/test/java/org/zalando/zmon/config/TestSecurityConfig.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/AlertServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/DashboardServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/HistoryServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplIT.java, zmon-controller-app/src/test/resources/test.properties, zmon-security-common/src/main/java/org/zalando/zmon/security/permission/DefaultZMonPermissionService.java
=> Cleanup Entity API and sort our create/update privileges

database/zmon/20_api/05_stored_procedures/11_create_or_update_entity.sql, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java
Return entity id even if we do not need to update anything as entity has not changed.
=> Fix 403 unmodified

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/directives/alertDeleteModal.js, zmon-controller-ui/templates/alertDeleteModal.html, zmon-controller-ui/views/alertDetails.html
- fixes typo on alertId for Evaluation and Cleanup.
- adds missing Alert Delete modal
=> Alert details fix

Dockerfile, pom.xml, zmon-common/src/main/java/org/zalando/zmon/domain/AlertDefinition.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/AlertDefinitionsApiIT.java
=> Make template property default false

zmon-controller-ui/templates/alertHistory.html
=> #289 give entity column more space

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js, zmon-controller-ui/views/alertDefinitionEditForm.html
=> #295 modify ui-select on alert edit for team and responsible team

.travis.yml
Travis does not package 9.5 yet...
=> install PostgreSQL 9.5 to fix Travis build

zmon-controller-ui/js/directives/dashboardWidget.js
#301 
include alert Ids of AlertStyles to check if those alerts are active
user doesn't require an alertsId array
=> #301 fix dashboard widget effects

Dockerfile
=> Use latest OpenJDK base image

zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/trialRun.html
=> fix documentation links

zmon-controller-app/src/main/java/org/zalando/zmon/api/SearchAPI.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java, zmon-controller-ui/js/directives/globalSearch.js
=> Implement team filter with the expected &team= query

zmon-controller-app/src/main/java/org/zalando/zmon/api/SearchAPI.java
#306: another PR to fix team filter....
=> #306 pass null to sproc to disable team filter

zmon-controller-ui/js/directives/globalSearch.js, zmon-controller-ui/js/services/CommunicationService.js
#306: use all the user's teams
=> #306 search with all teams, not just the first

zmon-security-common/src/main/java/org/zalando/zmon/security/service/PresharedTokensResourceServerTokenServices.java
To allow creating preshared tokens without a "proper" UID (i.e. without having a real user with groups in "user service").
=> allow overwriting the authority of a preshared token

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/directives/autofocus.js, zmon-controller-ui/js/directives/chart.js, zmon-controller-ui/js/directives/globalSearch.js, zmon-controller-ui/js/directives/keytrap.js, zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/styles/main.css, zmon-controller-ui/templates/globalSearch.html, zmon-controller-ui/views/dashboard.html
=> 306 global search

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionEditCtrl.js, zmon-controller-ui/views/checkDefinitionEditForm.html
=> 322 add ui select to check edit

zmon-controller-ui/grafana/public/plugins/grafana-kairosdb-datasource/datasource.js, zmon-controller-ui/grafana/public/plugins/grafana-kairosdb-datasource/query_ctrl.js
=> 325 kariosdb plugin tags

database/zmon/20_api/05_stored_procedures/60_create_or_update_check_definition.sql
Fix case handling to be ignored.
=> Fix owning team limit

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/HistoryServiceImpl.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java
=> Fixing the embed mode, dashboard-solo url

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/directives/caret.js, zmon-controller-ui/templates/globalSearch.html
=> #336 fix global search on firefox

zmon-controller-ui/js/controllers/DashboardDefinitionCtrl.js, zmon-controller-ui/views/dashboardDefinitions.html
=> #329 add infinite-scroll on dashboard list

zmon-controller-ui/js/directives/dashboardWidget.js, zmon-controller-ui/js/directives/gauge.js
=> #319 add format option to gauge widget value

zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/views/trialRun.html
=> #322 add ui-select owning team in TrialRun

zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java, zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractorTest.java
Yes some tests where just removed, but it is covered elsewhere.
=> Also apply role filter on API calls

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js
=> #339 set ACTIVE as default status for new alerts

zmon-controller-app/src/main/resources/templates/index.html
=> #342 limit to alphanumeric characters and avoid if Ctrl/Alt pressed

zmon-controller-ui/templates/globalSearch.html, zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/dashboard.html, zmon-controller-ui/views/history.html, zmon-github-integration/src/main/resources/templates/signin_github.html, zmon-zauth-integration/src/main/resources/templates/signin_zauth.html
We are running zmon behind our tools proxy which means that zmon lives under /app/zmon. 
This works well, however the links are not consistent and some of them link directly to the root, whereas most doesn't This makes them more consistent
=> Replace /#/ with #/ in order to make all links work behind a proxy

README.rst
=> Added Slack Chat badge

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/styles/main.css
=> #349 fix message manager css

zmon-controller-ui/grafana/public/plugins/grafana-kairosdb-datasource/datasource.js
=> #325 fix request for tags

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js
=> #339 fix alert new save

zmon-controller-ui/views/dashboardDefinitions.html
=> #329 fix dashboard infinite scroll

zmon-controller-ui/js/directives/globalSearch.js
=> #354 check for global search input field validation

zmon-controller-app/src/main/resources/templates/index.html
=> #342 avoid meta key on global search

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js
#364 
fixes issue where sometimes entities and/or exclude entities are not populated correctly and may show data from previous sessions.
=> #364 fix trial run entities

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/SimpleTeamServiceConfiguration.java, zmon-security-common/src/main/java/org/zalando/zmon/security/DynamicTeamService.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthAutoConfiguration.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthTeamService.java
Allow team config at runtime using entity.
=> Runtime config

zmon-controller-ui/js/directives/dashboardWidget.js
Apply styles first
Check if value is number before calling toFixed.
=> #359 fix "value" widget

zmon-security-common/src/main/java/org/zalando/zmon/security/DynamicTeamService.java
Mapping does not map fields for config
=> Make public for json mapper

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/controllers/DashboardCtrl.js, zmon-controller-ui/js/directives/alertDowntimes.js, zmon-controller-ui/js/directives/dashboardWidget.js, zmon-controller-ui/js/services/MainAlertService.js, zmon-controller-ui/templates/alertDowntimes.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/dashboard.html
=> 370 alert details inf scroll and optimizations on downtimes and dashboard

zmon-controller-ui/js/controllers/EntityCtrl.js, zmon-controller-ui/views/entities.html
=> Rendering capture or value if present, i like to see values over -since-

zmon-controller-app/src/main/resources/templates/index.html
=> #377 remove workers string from status bar

zmon-controller-app/src/main/java/org/zalando/zmon/config/CorsConfiguration.java
To allow hackweek project to access grafana
=> Enalbe CORS credentials

zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/EntityFilterRequest.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/EntityFilterResponse.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/ZMonService.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java, zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/js/services/CommunicationService.js, zmon-controller-ui/styles/main.css, zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/trialRun.html
=> 383 entity filter matches

zmon-controller-ui/js/controllers/CheckDefinitionEditCtrl.js
=> #383 show entity ids on check

zmon-controller-ui/styles/charts.css, zmon-controller-ui/styles/dashboard.css
=> 386 flot yaxis color

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/styles/forms.css, zmon-controller-ui/views/alertDetails.html
=> #389 add clipboard link with IP to copy to clipboard

run-dev.sh, zmon-controller-ui/styles/dashboard.css
=> #391 fix css on quicksearch by setting noWidgets container height to 0

database/zmon/20_api/05_stored_procedures/30_get_alert_definitions_by_team_and_tag.sql
=> support most basic ! for tags

database/zmon/20_api/05_stored_procedures/30_get_alert_definitions_by_team_and_tag.sql
=> Fix dashboard issue with null tags

pom.xml, zmon-controller-app/src/main/java/org/zalando/zmon/config/RedisPoolConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/redis/WriteRedisProperties.java
fixes #396 
Seems it was a bad idea to extend existing config-properties.
=> configproperties should not extend existing one

zmon-controller-app/src/main/resources/config/application.yml
=> Enable compression in controller

database/zmon/20_api/05_stored_procedures/60_onetime_access_tokens.sql
Fix/Implement outstanding feature of tokens having a seperate initial lifetime.
=> Validate oat_valid_until during session create

.travis.yml
=> Remove custom postgresql setup

zmon-controller-app/src/main/resources/db/migration/V5__get_all_check_definitions_update_with_schema.sql
Fixing placement of stored procedure.
=> Proper migration, earlier path was missing, injecting into data schema

zmon-controller-app/src/main/resources/db/migration/V6__get_active_alert_definitions_diff.sql
Return empty list if not alerts are present.
=> Fix nulls returned if no alert is present at all

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/AlertServiceImpl.java
Just timing this sproc to see if it makes sense to cache.
=> Intro timer around single sproc to see where time goes

zmon-controller-ui/styles/forms.css, zmon-controller-ui/templates/entityFilterForm.html
=> 408 entity filter form layout fix

zmon-controller-ui/test/karma.config.js, zmon-controller-ui/test/unit/alertDefinitionEditCtrl.spec.js, zmon-controller-ui/test/unit/trialRunCtrl.spec.js
=> 410 ui tests

scm-source.json, zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaControllerTest.java
Allows to overwrite dashboards for checks with custom grafana dashboards.
=> Overwrite dyn dashboards

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java
Remove log line, obvious spam for huge checks
=> Remove log line

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java
Fixing issues with user being able to save to dynamic dashboard which we don't want on the "normal" link.
=> Fixing dynamic dashboard properties

zmon-controller-ui/grafana/public/plugins/grafana-kairosdb-datasource/datasource.js
=> 422 grafana tag template autocomplete

pom.xml, zmon-common/src/main/java/org/zalando/zmon/domain/Alert.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/AlertController.java, zmon-controller-app/src/main/java/org/zalando/zmon/event/ZMonEventType.java, zmon-controller-app/src/main/java/org/zalando/zmon/redis/RedisPattern.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/AlertService.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/AlertServiceImpl.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/DowntimeServiceImpl.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-app/src/test/java/org/zalando/zmon/controller/AlertControllerTest.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/AlertServiceImplTest.java, zmon-controller-ui/js/directives/notificationModal.js, zmon-controller-ui/js/services/CommunicationService.js, zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/templates/notificationModal.html, zmon-controller-ui/views/dashboard.html
=> 421 notification acknowlege

zmon-controller-ui/js/app.js, zmon-controller-ui/js/controllers/AlertDetailsCtrl.js
=> 428 alertdetails filter permalink

zmon-controller-ui/templates/alertHistory.html
=> alert history timestamp fix

database/zmon/20_api/05_stored_procedures/55_grafana_sprocs.sql, zmon-controller-app/src/main/resources/db/migration/V9__Grafana_update.sql
=> Remove logging of dashboard.

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java
Grafana is now able to send metrics to AppDynamics.
=> Adds AppDynamics configuration to grafanaUI

zmon-controller-app/src/main/java/org/zalando/zmon/config/KairosDBProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/MultiKairosDBController.java
=> Capping relative queries for kairosdb

zmon-controller-app/src/main/java/org/zalando/zmon/controller/MultiKairosDBController.java
Show changed values during startup
=> Output config value

zmon-controller-app/src/main/resources/templates/index.html
=> #444 add google analytics

zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/GoogleanalyticsConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/GoogleanalyticsProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/index.html
=> 444 google analytics

zmon-controller-app/pom.xml, zmon-controller-it/pom.xml, zmon-zauth-integration/pom.xml
Supports new infrastructure out of the box
=> updates tokens to latest versions

zmon-controller-app/src/main/java/org/zalando/zmon/api/CheckDefinitionsApi.java
reported as https://github.com/zalando-zmon/zmon-cli/issues/54
=> add potential_solution field for the check

zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/InstanaConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/InstanaProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java
=> add instana eum

.gitignore
to prevent fullstop violations
=> add scm-source.json to gitignore

zmon-controller-ui/js/controllers/DashboardCtrl.js
Disable calls to /rest/checkResultsChart in the Dashboard controller.
=> INC-4664 disable checkResultsChart calls

zmon-controller-ui/styles/dashboard.css
Fixes overflowing text cc @mohabusama
=> Fix overflowing alert text

zmon-controller-ui/js/directives/dashboardWidget.js, zmon-controller-ui/js/services/CommunicationService.js
=> 493 bf check results

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/AlertServiceImpl.java, zmon-controller-ui/js/controllers/DashboardCtrl.js, zmon-controller-ui/js/services/CommunicationService.js, zmon-controller-ui/js/services/DowntimesService.js, zmon-controller-ui/views/dashboard.html
=> Allalerts change with limits

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/IndexCtrl.js
=> #512 move Index js code into IndexCtrl

zmon-controller-ui/templates/alertHistory.html
=> #471 set order By -time for reverse chronological order (newest first)

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js
=> #521 reset active alerts collection when no entities present

zmon-controller-ui/views/alertDetails.html
Addding detection for entity fields deeplink1 and deeplink2 to introduce arbitrary deep links from agent.
=> Support two basic entity deeplinks for alert details.

zmon-controller-ui/views/alertDetails.html
as above, improve rendering in alert details.
=> Move ng-if to div to render details properly.

zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-app/src/main/resources/templates/index.html
=> #463 add page tag for instana eum

Dockerfile
updated java startup to include javaagent configurations
=> updated java startup to include javaagent configurations

zmon-controller-app/pom.xml, zmon-controller-it/pom.xml
This version fixes zalando-stups/spring-boot-zalando-stups-tokens#33
=> Update to latest version of spring-boot-zalando-stups-tokens

zmon-controller-ui/views/alertDefinitionEditForm.html
the given value was not a valid time period
=> fix the example timeperiod value

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/DashboardCtrl.js, zmon-controller-ui/js/directives/windowTitle.js, zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/alertDefinitions.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/checkDefinitions.html, zmon-controller-ui/views/cloud.html, zmon-controller-ui/views/dashboard.html, zmon-controller-ui/views/dashboardConfiguration.html, zmon-controller-ui/views/dashboardDefinitions.html, zmon-controller-ui/views/entities.html, zmon-controller-ui/views/trialRun.html
=> #470 add window title

zmon-controller-ui/views/dashboardConfiguration.html
=> #470 dashboard edit view title

zmon-controller-ui/js/controllers/TrialRunCtrl.js
=> #540 remove localStorage use in TrialRun

zmon-controller-app/src/main/resources/templates/index.html
=> #544 remove instana eum

zmon-common/pom.xml, zmon-common/src/main/java/org/zalando/zmon/exception/AlertDefinitionNotFoundException.java, zmon-common/src/main/java/org/zalando/zmon/exception/CheckDefinitionNotFoundException.java, zmon-common/src/main/java/org/zalando/zmon/exception/CheckPermissionDeniedException.java, zmon-common/src/main/java/org/zalando/zmon/exception/DashboardNotFoundException.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/EntityFilterResponse.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/AlertController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/DashboardController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java
This pull request is created to update the error response code and a message for exceptional conditions in zmon controller. This pull request is work in progress.
=> First update for a couple of ZMonRestServices

run-dev.sh, zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/IndexCtrl.js, zmon-controller-ui/js/directives/tvLogoutModal.js, zmon-controller-ui/js/services/UserInfoService.js, zmon-controller-ui/templates/tvLogoutModal.html
=> #547 add tvLogoutModal directive and ENV var

Dockerfile, README.rst, delivery.yaml, zmon-controller-app/pom.xml
This is a work in progress and place holder for current work.
To be done - Location for external jar in dockerfile.
=> Opentracing instrumentation using external jar

zmon-controller-app/pom.xml, zmon-controller-app/src/main/java/org/zalando/zmon/config/EventLogConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/KairosDBConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/KairosDBProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/NotificationServiceProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/SchedulerProperties.java, zmon-zauth-integration/pom.xml, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthAuthorityService.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthTeamService.java
Tracing for Kairos, for some usages of Apache HTTP client, and so on.
=> Adds missing tracing bits

zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/cloud.html, zmon-controller-ui/views/dashboard.html, zmon-controller-ui/views/dashboardConfiguration.html
=> Text Input Latency fixes

zmon-controller-app/src/main/resources/templates/index.html
=> #457 add manual bootstraping of angularjs app to start after tracer init

zmon-controller-ui/views/alertDefinitionEditForm.html
=> #560 add ng-model debounce option on AlertDefinitionEdit

zmon-controller-ui/views/alertDetails.html
fixes https://github.com/zalando-zmon/zmon-controller/issues/569
=> add template hint on alerts page

delivery.yaml, zmon-controller-ui/js/controllers/AlertDefinitionCtrl.js, zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionCtrl.js, zmon-controller-ui/js/controllers/CloudCtrl.js, zmon-controller-ui/js/controllers/CloudEndpointsCtrl.js, zmon-controller-ui/js/controllers/DashboardCtrl.js, zmon-controller-ui/js/controllers/EntityCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js
=> #572 add location.replace

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/app.js, zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/js/directives/entityFilterContainer.js, zmon-controller-ui/js/directives/entityFilterForm.js, zmon-controller-ui/js/services/EntityFilterTypesService.js, zmon-controller-ui/lib/ng-debounce/ng-debounce.js, zmon-controller-ui/templates/entityFilterContainer.html, zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/trialRun.html
=> #560 add entity filter types service

zmon-controller-app/src/main/java/org/zalando/zmon/config/ConsentConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/ConsentProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/IndexCtrl.js, zmon-controller-ui/js/directives/consentModal.js, zmon-controller-ui/templates/consentModal.html
=> #582 add opt consent dialog feature

zmon-controller-app/src/main/resources/templates/index.html
#582 fix for when consent var is not defined
=> #582 js consent object always defined

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiTest.java
Added entity GLOBAL type check and required user error message
=> Added entity GLOBAL type check

zmon-controller-ui/styles/forms.css, zmon-controller-ui/styles/main.css
=> 472 alert details mobile fix

zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-ui/js/services/CommunicationService.js
=> 593 conditionally enable manual instr when auto instr is disabled

zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-ui/js/services/CommunicationService.js
=> 593 missing correct config path for tracer

zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-app/src/main/resources/templates/index.html
=> Removed AppDynamics & Instana Agents from UI

zmon-controller-ui/styles/dashboard.css
=> #458 - UI - Tick on Bell shifted to Triangle icon

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js
=> 520 ui inherit alert modal update

zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/views/dashboard.html
=> #458 - ui - minor changes in position

zmon-controller-ui/views/alertDefinitionEditForm.html, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/dashboardConfiguration.html, zmon-controller-ui/views/trialRun.html
=> 607 ui mark required fields

zmon-controller-ui/styles/forms.css, zmon-controller-ui/views/alertDetails.html
=> Made "Actions" col responsive for mobile view

zmon-controller-app/src/main/resources/templates/grafana.html
=> 593 fix context propagation on grafana manual instrumentation

zmon-controller-ui/views/trialRun.html
=> 613 ui change placeholder for name in trial run

zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/views/dashboardDefinitions.html
=> set the width of dashboard table

zmon-controller-ui/styles/dashboard.css
=> changed the width of modified date & name column

zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js
=> fixed entity lose issue for checks & alerts

zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/styles/forms.css
=> fixed icon visiblity issue

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/js/services/MainAlertService.js
=> 608 fix alert edit

zmon-controller-ui/js/controllers/AlertDefinitionEditCtrl.js
=> 608 fix for alert edit

zmon-controller-ui/js/directives/alertValueModal.js, zmon-controller-ui/js/directives/codeEditor.js, zmon-controller-ui/styles/main.css
=> formatted the exception

zmon-controller-ui/js/filters/UTCdate.js, zmon-controller-ui/templates/alertDowntimes.html, zmon-controller-ui/templates/alertHistory.html, zmon-controller-ui/templates/commentsModal.html, zmon-controller-ui/views/alertDetails.html, zmon-controller-ui/views/dashboardDefinitions.html, zmon-controller-ui/views/trialRun.html
=> changed 12hrs to 24 hrs time

run-dev.sh, zmon-controller-app/pom.xml, zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/SentryConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/SentryProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/resources/templates/index.html
Backend instrumentation with Sentry and configurations for UI instrumentation
=> Backend instrumentation with Sentry and configurations for UI instrumentation

zmon-controller-ui/styles/main.css
=> fixed : Wrapped the code text

zmon-controller-ui/views/changes.html
=> fixed time format for changes page

zmon-controller-app/src/test/java/org/zalando/zmon/api/AlertDefinitionsApiIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/config/TestSecurityConfig.java, zmon-controller-app/src/test/resources/test.properties, zmon-security-common/src/main/java/org/zalando/zmon/security/DynamicTeamService.java, zmon-security-common/src/main/java/org/zalando/zmon/security/permission/DefaultZMonPermissionService.java, zmon-security-common/src/main/java/org/zalando/zmon/security/permission/HasUpdateAlertDefinitionPermission.java, zmon-security-common/src/test/java/org/zalando/zmon/security/permission/DefaultZMonPermissionServiceTest.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthAuthorityService.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthTeamService.java, zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractorTest.java
=> Allow services add/update alerts

zmon-controller-app/src/test/java/org/zalando/zmon/config/TestSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthAutoConfiguration.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthAuthorityService.java, zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractorTest.java, zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/service/ZauthAuthorityServiceTest.java
=> decrease amount of requests to Teams API

delivery.yaml, pom.xml, zmon-controller-app/pom.xml, zmon-security-common/pom.xml, zmon-zauth-integration/pom.xml, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthAutoConfiguration.java
Issue: https://github.com/zalando-zmon/zmon-controller/issues/679
=> make controller deployable to nexus

zmon-controller-app/src/main/java/org/zalando/zmon/controller/MultiKairosDBController.java
to get some correlation which dashboards are actually used
=> log checkId and dashboard name for each request to KDB

run-dev.sh, zmon-security-common/pom.xml
Issue: https://github.com/zalando-zmon/zmon-controller/issues/689
=> fix run-dev

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java
not also those which failed because of permission problems (i.e. do not log attempts but just deletions)
=> log only deleted entities

zmon-controller-app/src/main/java/org/zalando/zmon/api/GrafanaDashboardAPI.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/GrafanaDashboardAPITest.java
`GrafanaDashboardAPI.getDashboards` was fetching data from DB but never returning it
=> fix GrafanaDashboardAPI.getDashboards to actually return data

zmon-controller-ui/js/directives/gauge.js, zmon-controller-ui/styles/dashboard.css, zmon-controller-ui/styles/main.css, zmon-controller-ui/templates/dashboardWidget.html
=> fix(dashboard): fix overlapping graph titles

zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
alertstate grafana plugin should have access to /rest/checkAlertResults etc endpoints
=> alertstate grafana plugin should have access to /rest/checkAlertResults etc endpoints

zmon-github-integration/src/main/java/org/zalando/github/zmon/config/ZmonGithubAutoConfiguration.java
declare TaskScheduler bean in ZmonGithubAutoConfiguration
=> declare TaskScheduler bean in ZmonGithubAutoConfiguration

zmon-controller-app/src/main/java/org/zalando/zmon/config/WebMvcConfig.java
add support for application/js media types to serve firebase js
=> add support for application/js media types to serve firebase js

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java
- Grafana6 redirect home
Signed-off-by: Rajat parida <rajatparida86@gmail.com>
=> Grafana6 redirect home

zmon-controller-ui/styles/main.css
=> change feedback button color

database/zmon/20_api/05_stored_procedures/15_get_entities_without_tag.sql, zmon-common/src/main/java/org/zalando/zmon/persistence/EntitySProcService.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java, zmon-controller-app/src/main/resources/db/migration/V14__sproc_get_entities_without_tag.sql
add fetching entities without a given tag name
=> Entities without tag

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java
Use reference type matching
Signed-off-by: Rajat parida <rajatparida86@gmail.com>
=> Fix empty string matching

zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/AlertResult.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/domain/AlertResults.java
=> fix: add getter/setter for converter (#712)

zmon-controller-app/src/main/java/org/zalando/zmon/config/SchedulerProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java
=> Increasing socket timeout for HTTP connections to scheduler

database/zmon/20_api/05_stored_procedures/14_delete_entities.sql, zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/main/resources/db/migration/V15__delete_entity.sql, zmon-controller-app/target/classes/db/migration/V15_delete_entity.sql
so we can actually see how long this was in use
=> dump deleted entities to check lifetime

zmon-controller-app/src/main/java/org/zalando/zmon/api/AlertStatusAPI.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/RestConfiguration.java, zmon-controller-app/src/main/resources/config/application-github.yml, zmon-controller-app/src/main/resources/config/application-local-test.yml, zmon-controller-app/src/main/resources/config/application.yml, zmon-controller-app/src/test/java/org/zalando/zmon/api/AlertStatusAPITest.java
=> fix: add ConfigurationProperties for RestConfiguration (#712)

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiTest.java
=> metrics for entity deletion by type

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java
Don't drop query params while redirecting to Grafana 6
=> Don't drop query params while redirecting to Grafana 6

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/main/resources/templates/grafana.html, zmon-controller-ui/pom.xml
Make sure Old grafana is still available
=> Make sure Old grafana is still available

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java, zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java
support zmon-check- dashboards in grafana 6 redirect
=> support zmon-check- dashboards in grafana 6 redirect

zmon-controller-app/src/main/resources/templates/grafana.html
=> fix static urls for grafana3

zmon-controller-app/src/main/java/org/zalando/zmon/config/CorsConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/AlertController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java
Drop OPTIONS from allowed methods
=> Drop OPTIONS from allowed methods

zmon-controller-app/src/main/java/org/zalando/zmon/api/SearchAPI.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/Grafana.java
Visualisation search fix. In the Grafana search API call:
- Always add `query`
- Only add `tag` if not empty
=> Visualisation search fix

zmon-controller-app/src/main/resources/templates/grafana.html
Use zmon endpoint instead of ztat
=> Use zmon endpoint instead of ztat

zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
whitelist checkResultsWithoutEntities for CORS
=> whitelist checkResultsWithoutEntities for CORS

zmon-controller-app/src/main/java/org/zalando/zmon/api/AlertStatusAPI.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/AlertResultsConfig.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/AlertStatusAPITest.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/AllowedFiltersConfigTest.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplTest.java
=> cleanup of getAlertResults

zmon-controller-app/src/main/java/org/zalando/zmon/api/FalsePositiveRateApi.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/MetaDataConfiguration.java, zmon-controller-app/src/main/java/org/zalando/zmon/config/MetaDataProperties.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/FalsePositiveRateService.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/FalsePositiveRateServiceImpl.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/FalsePositiveRateServiceImplTest.java
- API for FalsePositiveRate for alert(s)
=> FalsePositiveRates API implementation

zmon-controller-app/src/main/java/org/zalando/zmon/controller/FalsePositiveRateController.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/AlertDefinitionCtrl.js, zmon-controller-ui/js/directives/alertStats.js, zmon-controller-ui/js/services/CommunicationService.js, zmon-controller-ui/js/services/HttpResponseInterceptor.js, zmon-controller-ui/styles/main.css, zmon-controller-ui/templates/alertStats.html, zmon-controller-ui/views/alertDefinitions.html, zmon-controller-ui/views/alertDetails.html, zmon-github-integration/src/main/java/org/zalando/github/zmon/config/GithubSecurityConfig.java, zmon-security-common/src/main/java/org/zalando/zmon/security/ZmonResourceServerConfigurer.java, zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java
adds directive to display statistics about alerts, for now false positives percentage
=> False positive UI updates

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/FalsePositiveRateServiceImpl.java, zmon-controller-app/src/main/resources/config/application-zauth.yml, zmon-controller-ui/js/controllers/AlertDefinitionCtrl.js, zmon-controller-ui/styles/forms.css, zmon-controller-ui/views/alertDefinitions.html
Content:
- Create zmon token to make requests to metadata service
- Batch requests to metadata service while listing all alerts
- Typo fixes on AlertDef page
- Formatting fixes
=> Add token for metadata service

zmon-common/src/main/java/org/zalando/zmon/domain/MinCheckInterval.java, zmon-common/src/main/java/org/zalando/zmon/domain/SumMinuteChecks.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/IndexController.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/domain/FrontendBootData.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/FrontendBootDataService.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/FrontendBootDataServiceImpl.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java, zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-app/src/test/java/org/zalando/zmon/generator/CheckDefinitionImportGenerator.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplIT.java, zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplTest.java, zmon-controller-ui/js/app.js, zmon-controller-ui/js/controllers/CheckDefinitionEditCtrl.js, zmon-controller-ui/js/controllers/TrialRunCtrl.js, zmon-controller-ui/js/services/BootConfig.js, zmon-controller-ui/views/checkDefinitionEditForm.html, zmon-controller-ui/views/trialRun.html
Unless check is whitelisted
internal ref 389 and 391
Edge case where whitelisted check is TrialRun'd and attempted to be saved as a new check is handled on both FE and BE.
=> Minimum check interval should be one minute

zmon-common/src/main/java/org/zalando/zmon/domain/CheckDefinitionImport.java, zmon-controller-app/src/main/java/org/zalando/zmon/api/CheckDefinitionsApi.java
=> add criticality property to API

zmon-common/src/main/java/org/zalando/zmon/domain/MinCheckInterval.java, zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/FrontendBootDataServiceImpl.java
otherwise if entity doesn't exist, this will result in null pointer error on index.html
=> set safe default for min check interval data

zmon-controller-ui/js/controllers/CheckDefinitionCtrl.js, zmon-controller-ui/views/checkDefinitionView.html, zmon-controller-ui/views/checkDefinitions.html
add warning in check list and detail view to show actual execution interval
=> add warning in check list and detail view to show actual execution interval

zmon-controller-ui/templates/alertStats.html
set false positive info tooltip
=> set false positive info tooltip

zmon-common/src/main/java/org/zalando/zmon/domain/ServiceLevelStatus.java
set fixed set of service level status warnings
=> set fixed set of service level status warnings

zmon-controller-app/src/main/resources/templates/index.html, zmon-controller-ui/js/controllers/AlertDetailsCtrl.js, zmon-controller-ui/js/controllers/CheckDefinitionCtrl.js, zmon-controller-ui/js/services/ConfigurationService.js, zmon-controller-ui/views/alertDetails.html
additionaly moves the function to check wether an interval satisfies the min refresh rate condition
to it's own reusable service to avoid duplication
=> show min refresh rate for alerts

zmon-common/src/main/java/org/zalando/zmon/domain/ServiceLevelStatus.java
To support https://github.com/zalando-zmon/zmon-data-service/pull/137
=> support new SDL with sampled ingestion

zmon-common/pom.xml, zmon-common/src/main/java/org/zalando/zmon/domain/ServiceLevelStatus.java, zmon-common/src/test/java/org/zalando/zmon/domain/ServiceLevelStatusTest.java
Updates service level degradation status messages
=> updates service level degradation status messages

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/HistoryServiceImpl.java
add to list, so we can show all changes in the diff
=> description is multiline

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java, zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java, zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java
Reverts zalando-zmon/zmon-controller#782
For now revert, it causes too much CPU usage
=> Revert "Add Content-Type header to GET /api/v1/entities{,/*}"

Dockerfile
=> add jolokia agent to be able to monitor JVM stats

README.rst
add a message explaining the future direction of ZMON and its components
=> add deprecation header to README
