zalando-zmon/zmon-controller

zmon-controller-ui/views/dashboard.html

Time since last update is now visible on the compact dashboard mode, for each alert on the top right corner.

#74 show time since last update of alert on compact dashboard

---

zmon-controller-app/src/main/resources/templates/index.html

adds teams to popover with a limit of 5 teams and ellipsis, and removes no longer used "showSupportIcon" function.

#64 add teams to teams popover and limit to max 5 teams

---

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaController.java
zmon-controller-app/src/main/resources/grafana/dynamic-dashboard.json
zmon-controller-app/src/main/resources/grafana/home.json
zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaControllerTest.java

First attempt, not finished, but already allows to call `/grafana/dashboard/db/zmon-check-123`.

#147 dynamic Grafana dashboard for checks

---

zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-ui/js/directives/dropdown.js
zmon-controller-ui/styles/forms.css
zmon-controller-ui/styles/main.css
zmon-controller-ui/templates/dropdown.html
zmon-controller-ui/views/alertDefinitions.html
zmon-controller-ui/views/checkDefinitions.html
zmon-controller-ui/views/entities.html

adds directive that wraps a ui-bootstrap dropdown and adds an input field for filtering
replaces previous HTML on alertDefinitions, checkDefinitions and entities.
localStorage get/set, URL location update and selection of team is still part of the original controllers. This directive just renders HTML and gets a callback for a click event, so functionality on Controllers remains the same.
In the future, directive controller could be extended to use localStorage but for now this is ok.

 #144 add dropdown directive to be used in Team filter dropdowns

---

zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-ui/js/directives/autofocus.js
zmon-controller-ui/views/alertDefinitions.html
zmon-controller-ui/views/entities.html

Some browsers focus input fields on load if the attribute 'autofocus' is present. Sadly they only autofocus on load, so somethings focusing is not triggered (like when changing from Check definitions to Alert definitions).
A directive called Autofocus will replace this attribute and force focusing in an angularjs style.
Focusing on the dropdown team filter will be done in a separate issue, after ui-bootstrap has been updated to latest version.

#165 add autofocus directive

---

zmon-controller-app/pom.xml

remove kairosdb-client dependency

---

zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthProperties.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthTeamService.java

this allows us to add teams based on current team.
If team a splits into b,c we can add a to b and c.

Add team extension to tackle team changes

---

zmon-controller-app/src/main/java/org/zalando/zmon/controller/TvTokenController.java
zmon-security-common/src/main/java/org/zalando/zmon/security/jwt/JWTRememberMeServices.java
zmon-security-common/src/main/java/org/zalando/zmon/security/jwt/JWTService.java
zmon-security-common/src/main/java/org/zalando/zmon/security/rememberme/MultiRememberMeServices.java
zmon-security-common/src/main/java/org/zalando/zmon/security/rememberme/ZMonRememberMeServices.java
zmon-security-common/src/main/java/org/zalando/zmon/security/tvtoken/ZMonTvRememberMeServices.java

Set JWT cookie for TV tokens, too. This prevents hitting the database on every TV token request when not having session stickiness in the load balancer.

Tv token jwt cookie

---

zmon-security-common/src/main/java/org/zalando/zmon/security/jwt/JWTService.java

reduce log spam (JWT cookie is valid for 24h so a lot of cookies expire all the time) :smirk:

remove unnecessary "JWT expired" logging

---

zmon-controller-app/src/main/resources/grafana/home.json

adds refresh of 1m to Home dashboard
this should initialize the refresh value to 1m and stay like that after changing to other dashboards, although this wasn't tested, because of the lack of dashboards on local environment and the inability to create new ones.

#207 set Home dashboard refresh to 1m

---

database/zmon/20_api/05_stored_procedures/60_onetime_access_tokens.sql
run-dev.sh
zmon-common/src/main/java/org/zalando/zmon/domain/OnetimeTokenInfo.java
zmon-common/src/main/java/org/zalando/zmon/persistence/OnetimeTokensSProcService.java
zmon-controller-app/pom.xml
zmon-controller-app/src/main/java/org/zalando/zmon/api/OneTimeTokenApi.java
zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java
zmon-controller-app/src/main/java/org/zalando/zmon/controller/TvTokenController.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/MailService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/OneTimeTokenService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/TokenRequestResult.java
zmon-controller-app/src/main/resources/templates/by-email.html
zmon-controller-app/src/test/java/org/zalando/zmon/controller/TvTokenControllerTest.java
zmon-controller-ui/test/unit/cloudCtrl.spec.js
zmon-security-common/src/main/java/org/zalando/zmon/security/tvtoken/TvTokenService.java

Needs some merge of functionality in the service classes.
Basically you call:
```
https://demo.zmon.io/tv/by-email/user.name
```
And receive a token via e-mail to:
```
user.name@<configured domain>
```
The token must be used within one hour and if bound it lives only for 24h.
Combined with the JWT session this will make it work for max 48h @jbellmann.

Added initial work for mailing onetime tokens

---

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/downtimes/DowntimeAPIRequest.java

The downtime fields "commend" and "created_by" were mixed up in the constructor call.

fix field mapping for downtimes

---

database/zmon/20_api/05_stored_procedures/21_get_alert_last_modified_max.sql
database/zmon/20_api/05_stored_procedures/21_get_check_last_modified_max.sql
update-schema.sh
zmon-common/src/main/java/org/zalando/zmon/persistence/AlertDefinitionSProcService.java
zmon-common/src/main/java/org/zalando/zmon/persistence/CheckDefinitionSProcService.java
zmon-controller-app/src/main/java/org/zalando/zmon/api/AlertDefinitionsApi.java
zmon-controller-app/src/main/java/org/zalando/zmon/api/CheckDefinitionsApi.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/AlertService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/ZMonService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/AlertServiceImpl.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java

This way we can save a lot of full downloads for check and alert definitions all day long if nothing changes.

Added HEAD endpoint to retrieve last modified for check and alerts

---

zmon-controller-ui/js/directives/alertHistory.js
zmon-controller-ui/js/directives/alertValueModal.js
zmon-controller-ui/templates/alertHistory.html
zmon-controller-ui/views/alertDetails.html

Value field will be in most cases a stringified JSON object containing all "value" attributes of the event, for example:
`{"td":0.004593,"worker":"worker01","ts":1.472002343625695E9,"value":"ERROR: Command '['find', '/path/...', '-type', 'd', '-name', '.snapshot', '-prune', '-o', '-type', 'f', '-print', '-quit']' timed out after 2.0 seconds"}`

#289 add value field to alert history and remove User and Content fields

---

Dockerfile
zmon-controller-app/src/main/resources/config/application-zauth.yml
zmon-zauth-integration/pom.xml
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthAutoConfiguration.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthProperties.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/domain/Group.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthAuthorityService.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/service/ZauthTeamService.java

Fixes #291.
Tested locally with "zauth" profile. Users without a proper group will get kind of a signin redirect loop (authentication failes and it's logged).

#291 assign authorities based on groups from User Service

---

zmon-controller-ui/views/alertDetails.html

Solves issue #255, backend fails to add alert comments when an entity id is provided.
I do not consider this feature useful anyways, so best to remove it from the frontend.
Approve if you agree

#255 remove alert comments by entity

---

zmon-controller-app/src/main/resources/templates/index.html

#306: Use CTRL+S instead of ALT key (ALT key is used for regular text input on Mac).

#306 use CTRL+S instead of Alt (problematic for Mac users)

---

zmon-controller-app/src/main/resources/db/migration/V3__onetime_token_update.sql

Added a db migration to fix the onetime token sproc in case the old one is still present in existing deployments.

Make flyway migrate and fix the onetime token sproc

---

zmon-controller-app/src/main/resources/db/migration/V4__get_all_check_definitions_update.sql

If no checks in DB , we return null instead of empty list.
Gives ugly null pointer in scheduler.

Fix null returned if not checks in DB at all

---

zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-ui/js/directives/dashboardWidget.js
zmon-controller-ui/js/directives/gauge.js
zmon-controller-ui/js/services/FormatService.js
zmon-controller-ui/test/karma.config.js

#407 Replaces old format() used on Value and Gauge dashboard widgets with d3.format(), providing a full subset of Python's string formatting mini-language. (i.e. adds $ and %).

407 format value percent

---

zmon-controller-app/src/main/java/org/zalando/zmon/config/ControllerProperties.java
zmon-controller-app/src/main/java/org/zalando/zmon/config/EventLogConfiguration.java
zmon-controller-app/src/main/java/org/zalando/zmon/config/EventLogProperties.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/EventLogService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/EventLogServiceImpl.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/HistoryServiceImpl.java
zmon-controller-app/src/main/resources/config/application.yml
zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/EventLogServiceImplTest.java
zmon-security-common/src/main/java/org/zalando/zmon/security/service/PresharedTokensResourceServerTokenServices.java

supports #430 
Now communication with eventlog is more configurable and less hardcoded. Current filtered IDs are extracted from the code to application configuration

Make history filters configurable

---

zmon-controller-app/src/main/resources/config/application-zauth.yml
zmon-security-common/src/main/java/org/zalando/zmon/config/ZmonOAuth2Properties.java
zmon-security-common/src/test/java/org/zalando/zmon/config/ZmonOAuth2PropertiesTest.java
zmon-zauth-integration/pom.xml
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSocialConfigurer.java

supports #454 
Adds support or parameterisation of Oauth URLs `authorize-url` and `access-token-url`. Now one can include query parameters there.

Parameterise Oauth URLs

---

zmon-controller-ui/js/directives/dashboardWidget.js

small fix. Widget's latency notification (yellow border around and red font color) is getting triggered because its set to 30secs and now that is the new polling time. This increases the threshold to 60secs. #490

#490 fix dashboard widget latency notification warning (orange border)

---

zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/AlertServiceImpl.java

Use a default value for the OS env variable REDIS_SMEMBERS_COUNT in case it's not defined. Prevents an NPE at runtime. Default value was derived from the commit message of ac6e26f2.

Default value for REDIS_SMEMBERS_COUNT

---

zmon-controller-app/src/main/java/org/zalando/zmon/controller/TvTokenController.java
zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-app/src/test/java/org/zalando/zmon/controller/TvTokenControllerTest.java
zmon-security-common/src/main/java/org/zalando/zmon/security/jwt/JWTService.java
zmon-security-common/src/main/java/org/zalando/zmon/security/tvtoken/TvTokenService.java
zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZauthSecurityConfig.java

This adds a new drop-down menu item "Switch to TV mode" that allows regular users to convert their session into a TV/Wallboard mode.
- It logs out the real user and destroys its cookies;
- Creates a one time TV token
- Binds the current session to that TV token
After switching to TV mode the option to switch is no longer available.

added UI option to switch to TV mode

---

zmon-controller-ui/views/alertDefinitionEditForm.html

#577 ui-select element doesn't behave well with debounce ng-option on so this PR removes the option.

#577 removed debounce from ui-select elements on AlertDetailsEdit view

---

zmon-controller-ui/views/alertDetails.html

when an alert had caught an exception the value was just dropped raw in the table.
when you click on it now, it gets displayed in a modal

fix(AlertDetail): display captured exceptions in alert-value-modal

---

zmon-controller-app/src/main/java/org/zalando/zmon/config/CorsHeadersCleanerInterceptors.java
zmon-controller-app/src/main/java/org/zalando/zmon/config/KairosDBConfiguration.java

KairosDB returns CORS headers, which conflicts with CORS headers that `CorsConfiguration` sets on responses. `CorsHeadersCleanerInterceptors` strips CORS headers off proxied responses coming from KairosDB

add CorsHeadersCleanerInterceptors to strip CORS headers off proxied requests

---

zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java
zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java

query parameters (eg template variables) are not passed to grafana 6 in redirect

pass query params to grafana6

---

database/zmon/10_data/04_tables/80_grafana_mapping.sql
database/zmon/20_api/05_stored_procedures/95_get_grafana_mapping.sql
zmon-common/src/main/java/org/zalando/zmon/persistence/GrafanaDashboardSprocService.java
zmon-controller-app/src/main/java/org/zalando/zmon/controller/GrafanaUIController.java
zmon-controller-app/src/test/java/org/zalando/zmon/controller/GrafanaUIControllerTest.java

table is supposed to be filled by another project that moved dashboards to standalone Grafana
The reason behind needing this mapping is because ZMON recognizes Grafana dashboards by unique id (slugified from dashboard's first title), whereas Grafana 6 and higher use uid (eg. kjAm-vGZk) and slugs are fluid and change with dashboard title change. This mapping ties two unique identifiers together, so that redirection would work correctly

add grafana_mapping table that has mappings to Grafana dashboard uid

---

zmon-controller-app/src/main/java/org/zalando/zmon/api/AlertStatusAPI.java
zmon-controller-app/src/main/resources/config/application-github.yml
zmon-controller-app/src/main/resources/config/application-local-test.yml
zmon-controller-app/src/main/resources/config/application.yml

without the `}` the value is not used...

fix env setting for alert-results

---

zmon-common/src/main/java/org/zalando/zmon/domain/CheckDefinitionImport.java
zmon-common/src/main/java/org/zalando/zmon/domain/DefinitionRuntime.java

**Facts about java-sproc-wrapper**
[https://github.com/zalando-stups/java-sproc-wrapper](java-sproc-wrapper) is very strict when mapping database types to Java types. When there is an additional field in database type that is not present Java type it throws an exception. What is more it does the same when there is additional field in Java type but not in database type. However the latter can be suppressed by providing `partial = true` attribute to `@DatabaseType` annotation.
**Why is this needed?**
In order to provide a smooth rollout of future changes. When doing gradual deployment old version  is still there (some percentage of traffic) while new version made its db migration forward so the old version uses the new db schema for a while which would result in a crash without these …

Prepare zmon-controller for future changes (adding runtime)

---

zmon-controller-app/src/main/java/org/zalando/zmon/config/CheckRuntimeConfig.java
zmon-controller-app/src/main/java/org/zalando/zmon/controller/domain/CheckRuntimeConfigDto.java
zmon-controller-app/src/main/resources/db/migration/R__function_get_check_definition_history.sql
zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-app/src/test/java/org/zalando/zmon/checkruntime/CheckRuntimeDisabledIT.java
zmon-controller-app/src/test/java/org/zalando/zmon/checkruntime/CheckRuntimeEnabledIT.java
zmon-controller-ui/js/controllers/TrialRunCtrl.js
zmon-controller-ui/js/directives/checkRuntimeSelect.js
zmon-controller-ui/js/services/CommunicationService.js
zmon-controller-ui/templates/checkRuntimeSelect.html
zmon-controller-ui/views/alertDefinitionEditForm.html
zmon-controller-ui/views/checkDefinitionEditForm.html
zmon-controller-ui/views/trialRun.html

Part of a preparation for zmon-worker Python 3 migration.
Scope:
- add a directive that shows selection of runtime based on feature toggle configuration and initial runtime,
- add a config property to parametrize migration guide URL later,
- fix get history stored procedure for correct type (it's currently broken)
Depends on https://github.com/zalando-zmon/zmon-controller/pull/727

Add a runtime property to checks/alerts (frontend)

---

zmon-controller-app/src/main/java/org/zalando/zmon/controller/MultiKairosDBController.java

tag values in UTF-8 are properly returned but cannot be used for querying

enforce UTF-8 charset when proxying to KDB

---

zmon-controller-app/src/main/java/org/zalando/zmon/api/FalsePositiveRateApi.java
zmon-controller-app/src/main/java/org/zalando/zmon/controller/FalsePositiveRateController.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/FalsePositiveRateService.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/FalsePositiveRateServiceImpl.java

Use query params for getting AlertID list for listFalsePositiveRates instead of the request body

query params for querying AlertIDs for listFalsePositiveRates

---

zmon-controller-ui/styles/forms.css
zmon-controller-ui/views/alertDefinitions.html

the colunm in the alerts list is useful only in case the condition is something like 
```
> 1000
```
but this kind of alert defintions will not be supported by python3 workers, therefore it doesn't make a lot of sens to keep it.
this being said, we can increase the size of the other columns

removes condition column and adjusts other columns sizes

---

zmon-controller-ui/js/controllers/TrialRunCtrl.js

dependencies for TrialRunCtrl were specified at the bottom of the file, whereas function definition was at the top. This moves them together to the top and adds missing dependency - `BootConfig`

add missing dependency argument to TrialRunCtrl.js

---

zmon-zauth-integration/src/main/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractor.java
zmon-zauth-integration/src/test/java/org/zalando/zauth/zmon/config/ZmonAuthenticationExtractorTest.java

can be configurable through zmon-team-config entity

service users that belong to team ZMON should be admins

---

zmon-common/src/main/java/org/zalando/zmon/domain/ExecutionStatus.java
zmon-common/src/main/java/org/zalando/zmon/domain/ServiceLevelStatus.java
zmon-controller-app/src/main/java/org/zalando/zmon/service/impl/ZMonServiceImpl.java
zmon-controller-app/src/main/resources/templates/index.html
zmon-controller-app/src/test/java/org/zalando/zmon/service/impl/ZMonServiceImplIT.java
zmon-controller-ui/js/services/MainAlertService.js
zmon-controller-ui/styles/main.css

Adding the status of the service level config to the `/status` endpoint will enable the addition of a warning message within the UI in case of system degradation and enablement of resiliency measures.

adds service level config status to /status endpoint response

---

README.rst

The provided guidance for running zmon locally with Vagrant is deprecated, docker-compose should be used.

update local local running procedure in README

---

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java
zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java

eagleeye/ZMON#613 prohibit entity type change
If the type is changed, it could lead to different bugs.
Here are several changes which are worth to review:
- When we are trying to create or update an entity, we fetch it from DB by id. We need this because if the entity with such id exists (which means we are updating, not creating) we need to check the old type.
- The http error code is `409 Conflict`. The reason for not use `403 Forbidden` is that I would like to distinguish these cases for easier testing. If you think it is not a valid reason, don't hesitate to mention this in the comments.
- Feel free to say how understandable do you find the fluent approach I've used here (all this Optional/Stream stuff).

Prohibit entity type change

---

zmon-controller-ui/templates/alertHistory.html

this shows the history's captures when available - see also
https://github.com/zalando-zmon/zmon-data-service/pull/140
Signed-off-by: Hanno Hecker <hanno@zalando.de>

show captures from alertHistory events when available

---

zmon-controller-app/src/main/java/org/zalando/zmon/api/EntityApi.java
zmon-controller-app/src/main/java/org/zalando/zmon/controller/ZMonRestService.java
zmon-controller-app/src/test/java/org/zalando/zmon/api/EntityApiIT.java

so that clients depending on that header interpret the response as JSON.
Signed-off-by: Hanno Hecker <hanno@zalando.de>

Add Content-Type header to GET /api/v1/entities{,/*}
